name: Build and Deploy
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "packages/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          submodules: "true"

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
          
      - name: Use Node.js 24.x
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
        with:
          node-version: "24.x"

      - name: Install and Build OpenSCD
        run: |
          pnpm i @nx/nx-linux-x64-gnu
          pnpm clean-install
          pnpm run-script build
          pnpm run-script doc

      - name: Copy Core Docs to OpenSCD
        run: |
          cp -R packages/core/doc packages/distribution/build/core-doc

      - name: Copy Plugin Docs to OpenSCD
        run: |
          cp -R packages/plugins/doc packages/distribution/build/plugin-doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f #v4.8.0
        with:
          branch: master
          folder: packages/distribution/build
          repository-name: com-pas/openscd.github.io
          ssh-key: ${{ secrets.DEPLOY_KEY }}
